framework:
    asset_mapper:
        # Les chemins Asset Mapper. Ne pas référencer node_modules/ en prod
        # mutualisé (souvent absent) — flowbite est versionné sous assets/vendor/.
        paths:
            - assets/
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
