when@dev:
    web_profiler:
        toolbar:
            enabled: '%web_profiler.enabled%'

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
